timeout: 7200s

steps:
  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    id: utilscript
    args:
      - "util.sh"
    env:
      - "BUILD_ID=$BUILD_ID"
      - "PROJECT_ID=$PROJECT_ID"
      - "REVISION_ID=$REVISION_ID"
      - "BRANCH_NAME=$BRANCH_NAME"
      - "SHORT_SHA=$SHORT_SHA"
      - "REPO_NAME=$REPO_NAME"
    volumes:
      - name: "BuildTag"
        path: /workspace/buildTagName/
  # Install dependencies

  - name: node
    entrypoint: yarn
    id: install
    args: ["install"]

  # Run tests
  - name: node
    entrypoint: yarn
    id: test
    args: ["test"]

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    id: docker_build
    args:
      - -c
      - |
        BuildTag=$(cat /workspace/buildTagName/BuildTag.txt) &&
        docker build -t eu.gcr.io/ajit-gcd-project/git-demo:${BuildTag} .
        docker images
    volumes:
      - name: "BuildTag"
        path: /workspace/buildTagName/
  # image push
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    id: docker_push
    args:
      - -c
      - |
        BuildTag=$(cat /workspace/buildTagName/BuildTag.txt) &&
        docker push eu.gcr.io/ajit-gcd-project/git-demo:${BuildTag}
    volumes:
      - name: "BuildTag"
        path: /workspace/buildTagName/
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    id: "container_deploy"
    args:
      - -c
      - |
        gcloud config set project ajit-gcd-project &&
        echo "User : "
        gcloud auth list &&
        gcloud config set account '1028607869101@cloudbuild.gserviceaccount.com'
        BuildTag=$(cat /workspace/buildTagName//BuildTag.txt) &&
        gcloud run deploy ajit-gcd-project --image=eu.gcr.io/ajit-gcd-project/git-demo:${BuildTag} --region=europe-west1 --platform=managed --no-allow-unauthenticated
    volumes:
      - name: "BuildTag"
        path: /workspace/buildTagName/
